apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollouts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: 
    - missingkey=error
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/dtelaroli/argocd-simplified.git
                    revision: feature/mil
                    files:
                      - path: "environments/**/env.values.yaml"
                - git:
                    repoURL: https://github.com/dtelaroli/argocd-simplified.git
                    revision: feature/mil
                    files:
                      - path: "environments/**/platform/argo-rollouts.values.yaml"
          - git:
              repoURL: https://github.com/dtelaroli/argocd-simplified.git
              revision: feature/mil
              files:
                - path: "environments/global.values.yaml"
  template:
    metadata:
      name: "argo-rollouts-{{.env}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "platform-{{.env}}"
      source:
        repoURL: https://github.com/dtelaroli/argocd-simplified.git
        path: teams/platform/argo-rollouts
        targetRevision: '{{ .revisions.argoRollouts }}'
      destination:
        name: "{{ .clusterName }}"
        namespace: argo-rollouts
      syncPolicy:
        automated:
          selfHeal: false
          prune: false  
        syncOptions:
          - FailOnSharedResource=true
          - CreateNamespace=true
