apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: 
    - missingkey=error
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/dtelaroli/argocd-simplified.git
                    revision: HEAD
                    files:
                      - path: "environments/**/env.values.yaml"
                - git:
                    repoURL: https://github.com/dtelaroli/argocd-simplified.git
                    revision: HEAD
                    files:
                      - path: "environments/**/platform/istio-base.values.yaml"
          - git:
              repoURL: https://github.com/dtelaroli/argocd-simplified.git
              revision: HEAD
              files:
                - path: "environments/global.values.yaml"
  template:
    metadata:
      name: "istio-base-{{.env}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "platform-{{.env}}"
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: base 
        targetRevision: '{{ .revisions.istio }}'
        helm:
          version: v3
      destination:
        name: "{{ .clusterName }}"
        namespace: istio-system
      syncPolicy:
        automated:
          selfHeal: false
          prune: false
        syncOptions:
          - FailOnSharedResource=true
          - CreateNamespace=true
