apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-d
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: 
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/dtelaroli/argocd-simplified.git
              revision: feature/initial
              files:
                - path: "environments/**/global.values.yaml"
          - git:
              repoURL: https://github.com/dtelaroli/argocd-simplified.git
              revision: feature/initial
              files:
                - path: "environments/{{.env}}/platform/istio-d.values.yaml"
  template:
    metadata:
      name: "istio-d-{{.env}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: platform
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: istiod 
        targetRevision: "1.22.0"
        helm:
          version: v3
      destination:
        name: "{{ .name }}"
        namespace: istio-system
      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - FailOnSharedResource=true
          - CreateNamespace=true
