apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-api
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: 
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/dtelaroli/argocd-simplified.git
              revision: HEAD
              files:
                - path: "environments/**/global.values.yaml"
          - git:
              repoURL: https://github.com/dtelaroli/argocd-simplified.git
              revision: HEAD
              files:
                - path: "environments/{{.env}}/engineering/test-api.values.yaml"
  template:
    metadata:
      name: "test-api-{{ .env }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "engineering-{{ .env }}"
      source:
        repoURL: https://github.com/dtelaroli/argocd-simplified.git
        path: teams/engineering/test-api
        targetRevision: '{{ .revision | default "HEAD" }}'
        helm:
          version: v3
          valueFiles:
            - ../../../environments/{{ .env }}/global.values.yaml
            - values.yaml
            - ../../../environments/{{ .env }}/engineering/test-api.values.yaml
      destination:
        name: "{{ .clusterName }}"
        namespace: "{{ .env }}"
      syncPolicy:
        automated:
          selfHeal: false
          prune: false
        syncOptions:
          - FailOnSharedResource=true
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          managedFieldsManagers:
            - kube-controller-manager
          jsonPointers:
            - /spec/template/spec/source/helm/parameters
