apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - path: patches/argocd-cm.yaml
    target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
  - path: patches/argocd-cmd-params-cm.yaml
    target:
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
  - path: patches/argocd-rbac-cm.yaml
    target:
      version: v1
      kind: ConfigMap
      name: argocd-rbac-cm
  - path: patches/argocd-server.yaml
    target:
      version: v1
      kind: Deployment
      name: argocd-server
