name: Deploy PR
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
permissions: write-all
jobs:
  build:
    name: deploy pull-request
    if: ${{ github.event.issue.pull_request }} && ${{ contains(github.event.comment.body, 'actions[deploy]') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0             # otherwise, you will fail to push refs to dest repo
    - name: Set env
      env:
        NUMBER: ${{ github.event.issue.number }}
        REF: ${{ github.event.pull_request.head.ref }}
      run: |
        echo "TAG_NAME=PR-${NUMBER}" >> ${GITHUB_ENV}
        echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> ${GITHUB_ENV}
        echo "MANIFEST=./environments/dev/engineering/test-api.values.yaml" >> ${GITHUB_ENV}
    - name: Create manifest changes
      run: |
        env
        ./scripts/bash/set-release.sh ${{ env.BRANCH_NAME }} ${{ env.TAG_NAME }} ${{ env.MANIFEST }}
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        message: 'deploy pull-request: #${{ github.event.issue.number }}'
        branch: ${{ env.BRANCH_NAME }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

