name: Deploy release
on:
  release:
    types:
      - released
  workflow_dispatch:
permissions: write-all
jobs:
  build:
    name: deploy release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0             # otherwise, you will fail to push refs to dest repo
    - name: Set env
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> ${GITHUB_ENV}
        echo "MANIFEST=./environments/dev/engineering/test-api.values.yaml" >> ${GITHUB_ENV}
    - name: Create manifest changes
      run: |
        echo "./scripts/bash/set-release.sh ${{ env.RELEASE_VERSION }} ${{ env.RELEASE_VERSION }} ${{ env.MANIFEST }}"
        ./scripts/bash/set-release.sh ${{ env.RELEASE_VERSION }} ${{ env.RELEASE_VERSION }} ${{ env.MANIFEST }}
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        message: 'deploy release: ${{ env.RELEASE_VERSION }}'
        github_token: ${{ secrets.GITHUB_TOKEN }}
